# -*- coding: utf-8 -*-
"""Content data for the Dr. Johar's Plastic Surgery Group website.
Edit this file and re-run build.py to regenerate the site."""

SITE = {
    "name": "Dr. Johar's Plastic Surgery Group",
    "short": "Dr. Johar's",
    "doctor": "Dr. Manoj K Johar",
    "doctor_title": "Principal Director & Group Head — Plastic, Aesthetic & Reconstructive Surgery, Max Healthcare",
    "domain": "https://www.theaesthetic.in",
    "phone1": "+91 85277 78462",
    "phone1_raw": "+918527778462",
    "phone2": "+91 88604 44888",
    "phone2_raw": "+918860444888",
    "whatsapp": "918527778462",
    "email": "info@theaesthetic.in",
    "hours": "Mon – Sat · 10:00 AM – 6:00 PM",
    "social": {
        "facebook": "https://www.facebook.com/Dr-Johars-Plastic-Surgery-Group-101799121947317/",
        "instagram": "https://www.instagram.com/drjoharsplasticsurgerygroup/",
        "youtube": "https://www.youtube.com/channel/UCtuUKKIBk3TVPdZB5t1YzPA",
        "twitter": "https://twitter.com/DrManojJohar",
    },
    "tagline": "Committed to Excellence in Plastic & Reconstructive Surgery",
}

LOCATIONS = [
    {
        "name": "Max Multi Speciality Hospital, Noida",
        "short": "Noida",
        "address": "A-364, A Block, Pocket A, Sector 19, Noida, Uttar Pradesh 201301",
        "map": "https://maps.app.goo.gl/YP2hzaQBQLXAqaZV6",
        "embed": "https://www.google.com/maps?q=Max+Multi+Speciality+Hospital+Sector+19+Noida&output=embed",
        "primary": True,
    },
    {
        "name": "Max Super Speciality Hospital, Vaishali",
        "short": "Vaishali",
        "address": "W-3, Sector-1, Near Radisson Blu Hotel, Vaishali, Ghaziabad, Uttar Pradesh 201012",
        "map": "https://goo.gl/maps/GtaaoSbwnNQ7ELxi7",
        "embed": "https://www.google.com/maps?q=Max+Super+Speciality+Hospital+Vaishali&output=embed",
    },
    {
        "name": "Max Super Speciality Hospital, Patparganj",
        "short": "Patparganj",
        "address": "108A, I.P. Extension, Patparganj, Delhi 110092",
        "map": "https://goo.gl/maps/9WanjGoTf56hNRG17",
        "embed": "https://www.google.com/maps?q=Max+Super+Speciality+Hospital+Patparganj&output=embed",
    },
]

CREDENTIALS = [
    ("cred-association-of-plastic-surgeons-of-india.jpg", "Association of Plastic Surgeons of India"),
    ("cred-indian-association-of-aesthetic-plastic-surgeons.jpg", "Indian Association of Aesthetic Plastic Surgeons"),
    ("cred-international-college-of-surgeons.jpg", "International College of Surgeons"),
    ("cred-max-healthcare.jpg", "Max Healthcare"),
    ("cred-medical-concil-of-india.jpg", "Medical Council of India"),
    ("cred-medical-associations.jpg", "Medical Associations"),
]

TEAM = [
    {
        "slug": "dr-manoj-k-johar",
        "name": "Dr. Manoj K Johar",
        "role": "Principal Director & Group Head",
        "dept": "Plastic, Aesthetic & Reconstructive Surgery",
        "img": "dr-manoj-johar.jpg",
        "lead": True,
        "bio": [
            "Dr. Manoj K. Johar is a renowned cosmetic and plastic surgeon in Noida with extensive experience in both cosmetic and reconstructive procedures. He is dedicated to providing highly personalised care that meets the unique needs of each patient.",
            "Whether you are seeking cosmetic surgery to enhance your appearance or reconstructive surgery to address a medical condition, his compassionate approach and commitment to excellence have made him one of the most trusted plastic surgeons in the Delhi-NCR region.",
            "As Principal Director & Group Head at Max Healthcare, Dr. Johar leads a multidisciplinary team across three hospitals — Noida, Vaishali and Patparganj — offering the complete spectrum of surgical and non-surgical aesthetic treatments, complex reconstruction, craniofacial surgery, limb preservation and cancer reconstruction.",
        ],
        "expertise": ["Aesthetic & cosmetic surgery", "Breast surgery & reconstruction", "Craniofacial & cleft surgery", "Cancer reconstruction", "Limb preservation & amputation prevention", "Body contouring & liposuction", "Rhinoplasty & facial surgery", "Non-surgical rejuvenation"],
    },
    {"slug": "dr-rohit-chandra", "name": "Dr. Rohit Chandra", "role": "Principal Consultant", "dept": "Department of Plastic Surgery", "img": "dr-rohit-chandra.jpg",
     "bio": ["Dr. Rohit Chandra is a Principal Consultant in the Department of Plastic Surgery and a core member of Dr. Johar's Plastic Surgery Group. He works across aesthetic, reconstructive and microsurgical procedures with a focus on safe, natural-looking outcomes.",
             "He is closely involved in patient counselling, pre-operative planning and post-operative care, ensuring every patient receives continuity of care from consultation to complete recovery."],
     "expertise": ["Aesthetic surgery", "Reconstructive surgery", "Microsurgery", "Body contouring"]},
    {"slug": "dr-kamlesh-kumar", "name": "Dr. Kamlesh Kumar", "role": "Senior Consultant", "dept": "Department of Plastic Surgery", "img": "dr-kamlesh-kumar.jpg",
     "bio": ["Dr. Kamlesh Kumar is a Senior Consultant in the Department of Plastic Surgery. He brings wide experience in trauma reconstruction, burns, hand surgery and cosmetic procedures, and is known for his meticulous surgical technique.",
             "He is an integral part of the group's reconstructive and limb-preservation programmes."],
     "expertise": ["Trauma & burns reconstruction", "Hand surgery", "Cosmetic surgery", "Limb preservation"]},
    {"slug": "dr-lalit-agrawal", "name": "Dr. Lalit Agrawal", "role": "Senior Consultant", "dept": "Department of Plastic Surgery", "img": "dr-lalit-agrawal.jpg",
     "bio": ["Dr. Lalit Agrawal is a Senior Consultant in the Department of Plastic Surgery with a special interest in aesthetic surgery of the face and body, and in scar and wound management.",
             "He works closely with Dr. Johar on complex cases and leads many of the group's non-surgical and minimally invasive rejuvenation services."],
     "expertise": ["Facial aesthetic surgery", "Scar management", "Non-surgical rejuvenation", "Wound care"]},
    {"slug": "dr-sanjeev-dua", "name": "Dr. Sanjeev Dua", "role": "Senior Director", "dept": "Department of NeuroSciences", "img": "dr-sanjeev-dua.jpg",
     "bio": ["Dr. Sanjeev Dua is Senior Director in the Department of NeuroSciences and collaborates with Dr. Johar's group on craniofacial and cranio-synostosis surgery, skull-base reconstruction and complex head & neck cases.",
             "This multidisciplinary partnership allows children and adults with craniofacial conditions to receive coordinated neurosurgical and plastic-surgical care under one roof."],
     "expertise": ["Neurosurgery", "Craniofacial collaboration", "Skull-base reconstruction"]},
]

TESTIMONIALS = [
    {"name": "Irshadmohammed Shaikh", "for": "Chest wall deformity correction",
     "text": "My son Ibrahim was suffering from marfanoid habitus — his chest became abnormal, he felt uneasiness in breathing and had abnormal heart beats. Dr. Johar and his team treated him with great care and today he is doing well. We are truly grateful."},
    {"name": "Kanika Sharma", "for": "Skin treatment",
     "text": "I have always had a great experience. I trust him blindly — because of the change in my skin regime I have seen real improvement in my skin. Can't thank him enough."},
    {"name": "Ruchika Bansal", "for": "Cosmetic consultation",
     "text": "Very polite and experienced doctor. Good staff. Detailed interaction regarding the problem and treatment, and full assistance till the completion of treatment. Highly recommended."},
    {"name": "Ambika Kapur", "for": "Hair loss treatment",
     "text": "Excellent doctor, treats the problem from the core. I had lost my hair after Covid and with simple medicines he treated me where other doctors suggested so many therapies. Very happy with the results."},
]

VIDEOS = [
    {"img": "doctalk.jpg", "title": "DocTalk on Cosmetic Surgery, Part 1 — Dr. Manoj Johar", "cat": "DocTalk"},
    {"img": "doctalk.jpg", "title": "DocTalk on Cosmetic Surgery, Part 2 — Dr. Manoj Johar", "cat": "DocTalk"},
    {"img": "breast-reconstruction.jpg", "title": "Breast Reconstruction — Patient Testimonial", "cat": "Testimonial"},
    {"img": "pigeon-chest-surgery.jpg", "title": "Pigeon Chest Surgery | Rib Cage Deformity Treatment Through Thoracoplasty", "cat": "Case Story"},
    {"img": "craniosynostosis-treatment.jpg", "title": "Craniosynostosis Treatment Through Cosmetic Plastic Surgery", "cat": "Case Story"},
    {"img": "aesthetic-reconstructions-in-oral-cancers.jpg", "title": "Aesthetic Reconstructions in Oral Cancers", "cat": "Case Story"},
    {"img": "facial-reconstruction.jpg", "title": "Facial Reconstruction & Cosmetic Surgery | Aesthetic Plastic Surgery", "cat": "Case Story"},
    {"img": "bullet-hit-shoulder.jpg", "title": "Bullet Hit Shoulder — Complete Reconstruction Surgery", "cat": "Case Story"},
    {"img": "arshis-successful-finger-preservation.jpg", "title": "Arshi's Successful Finger Preservation Treatment", "cat": "Case Story"},
]

FAQS = [
    ("What is plastic surgery?", "Plastic surgery is a surgical specialty that restores, reconstructs or alters the human body. It has two broad arms: reconstructive surgery — which corrects defects caused by birth conditions, trauma, burns, infection or cancer — and aesthetic (cosmetic) surgery, which enhances appearance. Dr. Johar's group offers the complete spectrum of both."),
    ("Who is a good candidate for a procedure?", "Good candidates are in generally good health, have realistic expectations, are non-smokers (or willing to stop before surgery) and are seeking treatment for themselves rather than to please someone else. During your consultation Dr. Johar will assess your medical history, examine the area of concern and advise honestly whether a treatment is right for you."),
    ("What should I expect during the consultation?", "Your first visit is a detailed conversation. We listen to your goals, examine you, discuss the options — surgical and non-surgical — and explain the benefits, limitations, risks and recovery for each. You will receive a personalised plan and a transparent estimate before any decision is made."),
    ("What should I expect during treatment?", "Depending on the procedure, treatment may be performed under local anaesthesia in the clinic or under general anaesthesia at one of our Max Healthcare hospitals. Our team explains every step in advance — from pre-operative preparation and the day of surgery to what happens in the recovery room."),
    ("What is recovery like?", "Recovery varies widely — a filler or peel needs no downtime, while a body-contouring surgery may need 1–2 weeks of rest. You will be given written post-operative instructions, medications, and follow-up appointments, and you can always reach the team for any concern."),
    ("How much does treatment cost?", "Costs depend on the procedure, the technique required, anaesthesia and hospital stay. We give a clear, itemised estimate after your consultation. Please use the 'Know Your Estimate' option or contact us for an indicative range."),
    ("Will my insurance cover it?", "Reconstructive procedures — such as post-cancer reconstruction, trauma, cleft or burn surgery — are frequently covered by insurance. Purely cosmetic procedures are usually not covered. Our team will help you understand your policy and prepare the necessary documentation."),
    ("How can I reach you?", "Call +91 85277 78462 or +91 88604 44888, message us on WhatsApp, or book online. Dr. Johar consults at Max Hospitals in Noida, Vaishali and Patparganj."),
]

CATEGORIES = [
    {"slug": "surgical-treatments", "name": "Surgical Treatments", "short": "Surgical", "img": "surgeons-operating.jpg",
     "tag": "Reconstructive & aesthetic surgery",
     "desc": "Plastic surgery is a surgical specialty that aims to improve aesthetic appearance and function by reconstructing parts of the body damaged by burns, trauma, disease or congenital conditions — as well as refining features you were born with. Dr. Johar and his team perform the full range of aesthetic and reconstructive procedures at Max Healthcare hospitals.",
     "icon": "scalpel"},
    {"slug": "nonsurgical-treatments", "name": "Non-Surgical Treatments", "short": "Non-Surgical", "img": "facial-spa.jpg",
     "tag": "Minimal downtime, natural results",
     "desc": "We offer a range of non-surgical treatments that can help improve your appearance and let you look your best without surgery. After a thorough evaluation, Dr. Johar discusses the treatment options — injectables, lasers, peels, PRP, threads and more — that best suit your specific concern.",
     "icon": "sparkle"},
    {"slug": "cosmetic-medicine", "name": "Cosmetic Medicine", "short": "Cosmetic Medicine", "img": "cream-hand.jpg",
     "tag": "Medical skincare & maintenance",
     "desc": "Cosmetic medicine bridges dermatology and aesthetics: prescription skincare, medical facials, hair and skin health programmes and doctor-supervised regimens that keep skin healthy and slow visible ageing.",
     "icon": "leaf"},
    {"slug": "preventive-aesthetics", "name": "Preventive Aesthetics", "short": "Preventive", "img": "woman-smiling.jpg",
     "tag": "Start early, age gracefully",
     "desc": "Preventive aesthetics is about small, well-timed interventions in your 20s and 30s — sun protection, collagen-stimulating treatments, 'baby' Botox and skin-quality boosters — that delay the need for more significant procedures later.",
     "icon": "shield"},
    {"slug": "age-reversal", "name": "Age Reversal", "short": "Age Reversal", "img": "mature-woman.jpg",
     "tag": "Refresh, restore, rejuvenate",
     "desc": "Our age-reversal programmes combine surgical lifts, fat grafting, energy devices and injectables to restore volume, tighten skin and soften lines — with results that look rested and natural, never 'done'.",
     "icon": "clock"},
]

# --- Treatments -----------------------------------------------------------
# Every treatment: slug, name, cat, img, tagline, overview[], benefits[], candidates[], steps[(title,desc)], facts{}, faqs[(q,a)]

def T(slug, name, cat, img, tagline, overview, benefits, candidates, steps, facts, faqs, menu=None):
    return dict(slug=slug, name=name, cat=cat, img=img, tagline=tagline, overview=overview, benefits=benefits,
                candidates=candidates, steps=steps, facts=facts, faqs=faqs, menu=menu or name)

TREATMENTS = [
    # ---------------- SURGICAL ----------------
    T("amputation-prevention-limb-preservation", "Amputation Prevention & Limb Preservation", "surgical", "surgeons-operating.jpg",
      "Saving limbs, restoring function and independence.",
      ["Limb preservation is one of the most rewarding areas of reconstructive surgery. Diabetic foot ulcers, crush injuries, severe infections, vascular disease and cancer can all threaten a limb — and, historically, amputation was often the default answer.",
       "Dr. Johar's team uses advanced wound care, debridement, microvascular free-flap reconstruction and staged procedures to save limbs that might otherwise be lost. Working alongside vascular surgeons, orthopaedic surgeons and diabetologists at Max Healthcare, we build a plan around preserving function and mobility."],
      ["Avoids amputation where reconstruction is feasible", "Restores weight-bearing and mobility", "Reduces long-term disability and prosthesis dependence", "Coordinated multidisciplinary care under one roof"],
      ["Diabetic foot ulcers or non-healing wounds", "Traumatic or crush injuries with tissue loss", "Exposed bone, tendon or implants", "Limb-threatening infection or tumour resection"],
      [("Urgent assessment", "Wound evaluation, imaging and vascular studies to judge tissue viability."), ("Infection & wound control", "Debridement, negative-pressure therapy and antibiotics prepare the wound bed."), ("Reconstruction", "Skin grafts, local flaps or microvascular free flaps cover the defect and restore structure."), ("Rehabilitation", "Physiotherapy, offloading footwear and follow-up to prevent recurrence.")],
      {"Duration": "Varies by stage", "Anaesthesia": "General / regional", "Hospital stay": "As required", "Follow-up": "Long-term"},
      [("Is limb salvage always possible?", "Not always, but far more often than many patients are told. An early opinion from a reconstructive plastic surgeon greatly improves the odds — please do not wait until amputation is the only option."),
       ("Do you treat diabetic foot?", "Yes. Diabetic foot is one of the most common reasons patients are referred to us for limb preservation.")],
      "Amputation Prevention"),

    T("breast-surgery", "Breast Surgery", "surgical", "consultation.jpg",
      "Augmentation, reduction, lift and reconstruction — tailored to you.",
      ["Breast surgery spans a wide range of goals: enhancing size and shape (augmentation), relieving the physical burden of very large breasts (reduction), restoring youthful position (mastopexy / lift), correcting asymmetry, and rebuilding the breast after cancer surgery (reconstruction).",
       "Dr. Johar approaches every case with a detailed understanding of proportion, tissue quality and your personal goals. Implants, fat grafting or a combination may be recommended, and reconstruction can be performed at the time of mastectomy or later."],
      ["Improved proportion, symmetry and confidence", "Relief from back, neck and shoulder pain after reduction", "Restoration of the breast after mastectomy", "Natural-looking, long-lasting results"],
      ["Women seeking fuller or more balanced breasts", "Women with heavy, pendulous breasts causing discomfort", "Sagging after pregnancy, breastfeeding or weight loss", "Breast cancer patients before or after mastectomy"],
      [("Consultation & planning", "Measurements, discussion of implant type/size or fat grafting, and 3D planning where useful."), ("Surgery", "Performed under general anaesthesia at Max Hospital, usually 1.5–4 hours depending on procedure."), ("Recovery", "Supportive garment for a few weeks; most patients return to desk work in 7–10 days."), ("Follow-up", "Scar care and regular reviews to protect your long-term result.")],
      {"Duration": "1.5 – 4 hrs", "Anaesthesia": "General", "Hospital stay": "1 – 2 days", "Back to work": "7 – 14 days"},
      [("Will breast reduction be covered by insurance?", "Frequently yes, when there is documented physical symptoms. Reconstruction after cancer is generally covered. Cosmetic augmentation is not."),
       ("Can I breastfeed after breast surgery?", "Most techniques preserve the ability to breastfeed, but this should be discussed in your consultation as it depends on the procedure chosen.")]),

    T("cosmetic-surgery", "Cosmetic Surgery", "surgical", "hero-main.jpg",
      "Refined, natural enhancement of face and body.",
      ["Cosmetic (aesthetic) surgery enhances features you were born with or restores those changed by ageing, pregnancy or weight fluctuation. The aim is never to make you look different — it is to make you look like the best, most rested version of yourself.",
       "Dr. Johar offers the complete portfolio of aesthetic procedures — face, breast and body — using modern techniques that emphasise safety, minimal scarring and quick recovery. Every plan begins with an honest conversation about what surgery can and cannot achieve."],
      ["Personalised plan based on your anatomy and goals", "Modern techniques with reduced scarring and downtime", "Performed in accredited Max Healthcare operating theatres", "Long-term follow-up and support"],
      ["Adults in good general health with realistic expectations", "Non-smokers or those willing to stop before surgery", "Those seeking a specific, well-defined improvement", "Anyone who wants an expert opinion on the right procedure"],
      [("Consultation", "Understand your goals, examine, and discuss surgical and non-surgical options."), ("Planning", "Pre-operative tests, photographs and a clear written estimate."), ("Surgery", "Day-care or short-stay procedures at Max Hospital."), ("Recovery & follow-up", "Structured aftercare until your final result matures.")],
      {"Duration": "Procedure-specific", "Anaesthesia": "Local / general", "Hospital stay": "Day-care – 2 days", "Results": "Long-lasting"},
      [("Which cosmetic procedures do you offer?", "Rhinoplasty, facelift, blepharoplasty, brow lift, facial implants, gynaecomastia correction, liposuction, tummy tuck, arm and thigh lifts, body contouring, breast surgery, hair transplant and more."),
       ("How do I know which procedure is right for me?", "That is exactly what the consultation is for. Dr. Johar will guide you towards the least invasive option that meets your goal.")]),

    T("hair-transplant", "Hair Transplant", "surgical", "hair-care.jpg",
      "Permanent, natural hairline restoration.",
      ["A hair transplant relocates your own healthy hair follicles — usually from the back and sides of the scalp — to areas of thinning or baldness. Because these follicles are genetically resistant to hair loss, the results are permanent.",
       "We use follicular unit extraction (FUE) and follicular unit transplantation (FUT) depending on your hair type, the extent of loss and your goals. Careful hairline design and single-follicle placement at the front are the keys to a natural, undetectable result."],
      ["Permanent, natural-looking hair growth", "Minimally invasive FUE with no linear scar", "Custom hairline design suited to your face and age", "Can also restore eyebrows, beard and scars"],
      ["Men and women with pattern hair loss", "Adequate donor hair density", "Stable hair loss (usually 25+ years of age)", "Realistic expectations about density"],
      [("Assessment", "Scalp examination, donor evaluation and grafts estimation."), ("Procedure", "Under local anaesthesia; grafts are extracted and implanted over 4–8 hours."), ("Early recovery", "Small scabs fall off in 7–10 days; transplanted hairs shed before regrowth."), ("Results", "New growth from 3–4 months; full result at 12 months.")],
      {"Duration": "4 – 8 hrs", "Anaesthesia": "Local", "Hospital stay": "None (day-care)", "Results": "Visible at 6–12 months"},
      [("FUE or FUT — which is better?", "Both give excellent results. FUE avoids a linear scar and suits shorter hairstyles; FUT can harvest more grafts in one sitting. Dr. Johar recommends based on your needs."),
       ("Is it painful?", "The procedure is done under local anaesthesia and is comfortable. Mild soreness for a day or two is easily managed.")]),

    T("brow-lift", "Brow Lift", "surgical", "face-natural.jpg",
      "Open the eyes, soften the frown, look rested.",
      ["A brow lift (forehead lift) elevates drooping brows, softens horizontal forehead lines and reduces the heavy, tired look that develops as the brow descends with age. It is often combined with eyelid surgery for a complete upper-face rejuvenation.",
       "Depending on your anatomy, Dr. Johar may recommend an endoscopic brow lift through tiny incisions hidden in the hair, a temporal (lateral) lift, or a direct lift. Non-surgical alternatives such as Botox or thread lifts are discussed where suitable."],
      ["Refreshed, more open eyes", "Smoother forehead and softened frown lines", "Hidden incisions within the hairline", "Long-lasting results"],
      ["Sagging or asymmetric brows", "Deep forehead furrows or frown lines", "Hooding of the upper eyelids caused by the brow", "Good general health, non-smoker"],
      [("Consultation", "Assessment of brow position, forehead height and eyelid skin."), ("Surgery", "Endoscopic or open technique under anaesthesia; 1–2 hours."), ("Recovery", "Swelling and bruising settle in 1–2 weeks."), ("Result", "Final position visible after a few weeks; lasts many years.")],
      {"Duration": "1 – 2 hrs", "Anaesthesia": "Local with sedation / general", "Hospital stay": "Day-care", "Back to work": "7 – 10 days"},
      [("Will I look surprised?", "No. Modern brow lifting is conservative — the goal is a natural, rested brow, not an over-elevated one."),
       ("Can Botox do the same thing?", "Botox can lift the brow subtly by a few millimetres and is a good option for mild cases; surgery gives a more significant, lasting change.")]),

    T("blepharoplasty-eyelid-surgery", "Blepharoplasty (Eyelid Surgery)", "surgical", "skin-closeup.jpg",
      "Brighter, younger eyes — upper, lower or both.",
      ["Blepharoplasty removes or repositions excess skin, muscle and fat of the eyelids. Upper-lid surgery corrects hooding that can even obstruct vision; lower-lid surgery treats bags and puffiness under the eyes.",
       "Incisions are placed in the natural crease of the upper lid or just below the lash line (or inside the lower lid), so scars are virtually invisible. The result is a fresher, more alert appearance without changing the character of your eyes."],
      ["Removes hooding and under-eye bags", "Improves peripheral vision in severe upper-lid hooding", "Almost invisible scars", "Quick recovery"],
      ["Excess upper-eyelid skin", "Puffiness or bags under the eyes", "Tired-looking eyes despite adequate rest", "Healthy adults without serious eye conditions"],
      [("Consultation", "Eye and eyelid examination, discussion of upper/lower or combined surgery."), ("Surgery", "Under local anaesthesia with sedation; 45–90 minutes."), ("Recovery", "Cold compresses; sutures out in 5–7 days; bruising fades in ~2 weeks."), ("Result", "Refreshed eyes lasting many years.")],
      {"Duration": "45 – 90 min", "Anaesthesia": "Local + sedation", "Hospital stay": "Day-care", "Back to work": "5 – 7 days"},
      [("Will the shape of my eyes change?", "No — a good blepharoplasty removes the excess but keeps your natural eye shape."),
       ("Can I have it with a brow lift?", "Yes, upper-face procedures are commonly combined for a harmonious result.")],
      "Blepharoplasty (Eyelid)"),

    T("rhinoplasty-nose-job", "Rhinoplasty (Nose Job)", "surgical", "woman-pink.jpg",
      "Balance, refinement and better breathing.",
      ["Rhinoplasty reshapes the nose to bring it into harmony with the rest of the face — reducing a hump, refining the tip, narrowing the bridge or nostrils, correcting asymmetry after injury, or improving breathing by straightening a deviated septum (septorhinoplasty).",
       "Dr. Johar favours a structural, preservation-minded approach that supports the nose for the long term. Open or closed techniques are chosen case by case, and results are designed to look natural for your ethnicity and features."],
      ["Improved facial balance and profile", "Corrects breathing problems alongside appearance", "Natural results that suit your face", "Precise, structural technique for lasting shape"],
      ["Dissatisfaction with nose size, shape or symmetry", "Nasal deformity after trauma", "Breathing difficulty from a deviated septum", "Facial growth complete (usually 17+ years)"],
      [("Consultation & imaging", "Nasal analysis, photos and discussion of realistic goals."), ("Surgery", "Under general anaesthesia; 2–3 hours."), ("Recovery", "External splint for 7 days; most swelling settles in 4–6 weeks."), ("Refinement", "The tip continues to refine for up to 12 months.")],
      {"Duration": "2 – 3 hrs", "Anaesthesia": "General", "Hospital stay": "Day-care / 1 night", "Back to work": "7 – 10 days"},
      [("Will there be visible scars?", "Closed rhinoplasty has no external scar; open rhinoplasty leaves a tiny, well-hidden scar under the columella that fades to near-invisibility."),
       ("Is revision rhinoplasty possible?", "Yes. Dr. Johar sees many patients for revision of earlier surgery — these are complex cases and are planned carefully.")],
      "Rhinoplasty (Nose Job)"),

    T("facelift", "Facelift", "surgical", "mature-woman.jpg",
      "Lift the years away — naturally.",
      ["A facelift (rhytidectomy) repositions sagging deeper tissues (the SMAS), removes excess skin and restores definition to the jawline, cheeks and neck. Modern facelifting is about lifting and repositioning, not pulling — so results look rested rather than tight.",
       "Depending on your concerns, Dr. Johar may recommend a mini or short-scar facelift, a full SMAS facelift, a neck lift, or a combination with fat grafting, eyelid surgery or laser resurfacing for a complete rejuvenation."],
      ["Defined jawline and neck", "Softened nasolabial folds and jowls", "Natural, long-lasting rejuvenation (8–10 years)", "Incisions hidden around the ear and hairline"],
      ["Sagging of the mid-face, jowls or neck", "Loose skin that non-surgical treatments cannot address", "Good skin elasticity for the best result", "Non-smokers in good health"],
      [("Consultation", "Facial analysis and discussion of the right type of lift."), ("Surgery", "Under general anaesthesia; 3–5 hours depending on extent."), ("Recovery", "Dressings and drains for 1–2 days; presentable in 2 weeks."), ("Result", "Settles fully over 3 months; lasts many years.")],
      {"Duration": "3 – 5 hrs", "Anaesthesia": "General", "Hospital stay": "1 – 2 nights", "Back to work": "2 – 3 weeks"},
      [("Will I look 'pulled'?", "No. SMAS-based techniques lift the deeper layer so the skin is never under tension — that is what keeps the result natural."),
       ("What is the best age for a facelift?", "There is no fixed age; most patients are between 45 and 70. The right time is when sagging bothers you and non-surgical options no longer help.")]),

    T("facial-implants", "Facial Implants", "surgical", "woman-dark.jpg",
      "Definition for chin, cheeks and jaw.",
      ["Facial implants add permanent structure and definition to a weak chin, flat cheeks or an under-projected jaw. Made of medical-grade silicone or porous polyethylene, they are placed through hidden incisions inside the mouth or under the chin.",
       "Chin augmentation is frequently combined with rhinoplasty to balance the profile. Fat grafting and fillers are alternatives that Dr. Johar will discuss with you."],
      ["Permanent improvement in facial proportion", "Hidden incisions with no visible scars", "Quick, day-care procedure", "Can be combined with rhinoplasty or facelift"],
      ["Receding or weak chin", "Flat cheekbones or mid-face volume loss", "Desire for a stronger jawline", "Facial growth complete"],
      [("Consultation", "Facial analysis, implant selection and sizing."), ("Surgery", "Under local anaesthesia with sedation or general; ~1 hour."), ("Recovery", "Swelling for 1–2 weeks; soft diet if intra-oral incision."), ("Result", "Immediate, permanent definition.")],
      {"Duration": "~1 hr", "Anaesthesia": "Local + sedation / general", "Hospital stay": "Day-care", "Back to work": "5 – 7 days"},
      [("Are implants safe?", "Yes; facial implants have decades of safety data. Infection or displacement are rare and treatable."),
       ("Can they be removed?", "Yes, implants are removable if ever desired.")]),

    T("gynaecomastia", "Gynaecomastia (Male Breast Reduction)", "surgical", "operating-room.jpg",
      "A flatter, firmer, more masculine chest.",
      ["Gynaecomastia — enlargement of male breast tissue — is very common and can be a source of real embarrassment. It may be caused by hormonal changes, medications, weight gain or have no identifiable cause.",
       "Surgery combines liposuction to remove fat with direct excision of the firm glandular tissue through a small incision at the edge of the areola. The result is a flat, contoured chest with barely visible scarring."],
      ["Flat, masculine chest contour", "Tiny, well-hidden scars", "Day-care surgery with quick recovery", "Boost in confidence — swim and dress freely"],
      ["Persistent breast enlargement in men", "Failure to improve with diet and exercise", "Stable weight", "Adolescents after growth is complete"],
      [("Consultation", "Examination, sometimes hormone tests or ultrasound."), ("Surgery", "Liposuction + gland excision under general anaesthesia; 1–2 hours."), ("Recovery", "Compression vest for 4–6 weeks; back to work in a few days."), ("Result", "Final contour at 3 months.")],
      {"Duration": "1 – 2 hrs", "Anaesthesia": "General", "Hospital stay": "Day-care", "Back to work": "3 – 5 days"},
      [("Will it come back?", "Once the gland is removed it does not regrow. Significant weight gain can add fat, so a stable lifestyle protects your result."),
       ("Is there a scar?", "A small incision at the areolar border heals to a fine line that is very hard to see.")]),

    T("arm-reduction-lift", "Arm Reduction / Lift (Brachioplasty)", "surgical", "body-fitness.jpg",
      "Trim, toned upper arms.",
      ["An arm lift removes loose, hanging skin and fat from the upper arms — often after weight loss or with age. Liposuction alone can help mild cases; when skin has lost its elasticity, excision is needed.",
       "The incision runs along the inner arm where it is least visible. Dr. Johar tailors the length of the scar to the amount of correction needed, from a short scar in the armpit to a full-length lift."],
      ["Firmer, slimmer upper arms", "Freedom to wear sleeveless clothing", "Combined with liposuction for best contour", "Scar placed on the inner arm"],
      ["Sagging skin of the upper arms", "Significant weight loss", "Stable weight for 6+ months", "Non-smoker in good health"],
      [("Consultation", "Skin and fat assessment; choice of limited or full brachioplasty."), ("Surgery", "Under general anaesthesia; 2–3 hours."), ("Recovery", "Compression garment; light activity in 1–2 weeks."), ("Result", "Scars mature over 12 months.")],
      {"Duration": "2 – 3 hrs", "Anaesthesia": "General", "Hospital stay": "Day-care / 1 night", "Back to work": "1 – 2 weeks"},
      [("Will the scar be visible?", "It runs along the inner arm and fades significantly with scar care, but a fine line remains — most patients feel it is a very worthwhile trade.")],
      "Arm Reduction / Lift"),

    T("thigh-reduction-lift", "Thigh Reduction / Lift", "surgical", "body-fitness.jpg",
      "Smoother, firmer thighs.",
      ["A thigh lift removes excess skin and fat from the inner or outer thighs, producing smoother, better-proportioned contours. It is most commonly requested after major weight loss.",
       "The incision for an inner thigh lift is hidden in the groin crease; more extensive lifts extend along the inner thigh. Liposuction is usually combined to refine the shape."],
      ["Firmer inner and outer thighs", "Less chafing and improved comfort", "Better-fitting clothing", "Combined with liposuction for a sculpted look"],
      ["Loose thigh skin after weight loss or ageing", "Stable weight for 6+ months", "Good general health", "Realistic expectations about scarring"],
      [("Consultation", "Assessment of skin laxity and fat distribution."), ("Surgery", "Under general anaesthesia; 2–3 hours."), ("Recovery", "Compression garment; walking encouraged from day one."), ("Result", "Final contour by 3–6 months.")],
      {"Duration": "2 – 3 hrs", "Anaesthesia": "General", "Hospital stay": "1 night", "Back to work": "2 weeks"},
      [("How is the scar hidden?", "For most patients the incision sits in the groin crease and is covered even by underwear.")]),

    T("body-contouring", "Body Contouring", "surgical", "body-fitness.jpg",
      "Sculpting the body after weight loss or pregnancy.",
      ["Body contouring is a family of procedures — liposuction, tummy tuck, arm and thigh lifts, body lift, breast lift — that reshape the body by removing excess fat and skin. It is especially transformative after massive weight loss, when the skin can no longer shrink back.",
       "Dr. Johar creates a staged plan that prioritises the areas that bother you most, spacing surgeries safely and combining them where sensible."],
      ["Comprehensive reshaping of trunk, arms, thighs and chest", "Restores proportion after weight loss", "Staged, safe planning across procedures", "Long-lasting when weight is stable"],
      ["Loose skin after weight loss or pregnancy", "Stable weight for 6–12 months", "Non-smoker in good health", "Committed to a healthy lifestyle"],
      [("Consultation", "Whole-body assessment and prioritisation of areas."), ("Staged surgery", "One or two areas per session under general anaesthesia."), ("Recovery", "Compression garments and graded return to activity."), ("Maintenance", "Stable weight keeps results for years.")],
      {"Duration": "2 – 6 hrs per stage", "Anaesthesia": "General", "Hospital stay": "1 – 3 nights", "Back to work": "2 – 3 weeks"},
      [("Can everything be done at once?", "Safety comes first: procedures are combined only when the total operating time and blood loss are acceptable. Many patients have two or three stages.")]),

    T("abdominoplasty-tummy-tuck-mommy-makeover", "Abdominoplasty / Tummy Tuck / Mommy Makeover", "surgical", "woman-smiling.jpg",
      "A flat, firm abdomen — and a full post-pregnancy restoration.",
      ["An abdominoplasty (tummy tuck) removes loose skin and fat from the lower abdomen and tightens separated abdominal muscles (diastasis recti) that pregnancy or weight change leave behind. The result is a flatter, firmer waistline that exercise alone cannot achieve.",
       "A Mommy Makeover combines a tummy tuck with breast surgery (lift, augmentation or reduction) and liposuction, restoring the pre-pregnancy figure in a single, coordinated plan."],
      ["Flat abdomen and repaired muscle wall", "Improved posture and core strength", "Removes stretch marks below the navel", "One recovery period for multiple procedures"],
      ["Loose abdominal skin after pregnancy or weight loss", "Muscle separation causing a bulge", "Finished having children (recommended)", "Stable weight, non-smoker"],
      [("Consultation", "Examine skin, fat and muscle; plan mini or full tuck ± other procedures."), ("Surgery", "Under general anaesthesia; 2–5 hours."), ("Recovery", "Walk bent for a few days; garment for 6 weeks; drive at 2 weeks."), ("Result", "Final shape at 3–6 months; scar low and hidden.")],
      {"Duration": "2 – 5 hrs", "Anaesthesia": "General", "Hospital stay": "1 – 2 nights", "Back to work": "2 – 3 weeks"},
      [("Where is the scar?", "Low across the abdomen, within the bikini line — planned to be hidden by underwear or swimwear."),
       ("Can I get pregnant after a tummy tuck?", "Yes, but a future pregnancy can stretch the result — which is why we recommend it after you have completed your family.")],
      "Tummy Tuck / Mommy Makeover"),

    T("liposuction", "Liposuction", "surgical", "body-fitness.jpg",
      "Targeted fat removal for stubborn areas.",
      ["Liposuction removes localised fat deposits that resist diet and exercise — abdomen, flanks, thighs, arms, chin, back and knees. It is a contouring procedure rather than a weight-loss method, and works best when skin still has good elasticity.",
       "We use tumescent, power-assisted and energy-assisted techniques through tiny incisions. High-definition liposculpture can also etch athletic definition in suitable patients."],
      ["Precise reshaping of problem areas", "Tiny incisions, minimal scarring", "Day-care procedure", "Fat can be re-used for grafting (face, breast, buttocks)"],
      ["Localised fat with good skin tone", "Within ~30% of ideal body weight", "Healthy, non-smoker", "Realistic expectations"],
      [("Consultation", "Marking areas, assessing skin quality."), ("Procedure", "Under local, regional or general anaesthesia; 1–3 hours."), ("Recovery", "Compression garment for 4–6 weeks; back to work in days."), ("Result", "Swelling settles over 6–12 weeks.")],
      {"Duration": "1 – 3 hrs", "Anaesthesia": "Local / general", "Hospital stay": "Day-care", "Back to work": "3 – 7 days"},
      [("Does the fat come back?", "Removed fat cells do not return; remaining cells can enlarge with weight gain, so a stable weight preserves the result."),
       ("How much fat can be removed?", "For safety, a limited volume is removed in one session; large volumes may be staged.")]),

    T("cancer-reconstruction-surgery", "Cancer Reconstruction Surgery", "surgical", "surgeons-operating.jpg",
      "Rebuilding form and function after cancer.",
      ["Removing a tumour can leave significant defects of the breast, head and neck, jaw, limbs or trunk. Reconstructive surgery restores appearance and function — allowing patients to eat, speak, walk and face the world with confidence.",
       "Dr. Johar's team works within Max Healthcare's oncology programme, performing immediate or delayed reconstruction using implants, local flaps and microvascular free tissue transfer. Aesthetic reconstruction in oral cancers is a particular area of expertise."],
      ["Restores appearance and function after tumour surgery", "Microvascular free flaps for complex defects", "Coordinated with the oncology team", "Immediate reconstruction at the time of resection where possible"],
      ["Breast cancer patients (mastectomy or lumpectomy)", "Head & neck / oral cancer resections", "Skin cancer and soft-tissue tumours", "Limb-preserving tumour resection"],
      [("Joint planning", "Reconstruction is planned with the cancer surgeon before resection."), ("Reconstruction", "Flap or implant reconstruction, often in the same operation."), ("Recovery", "Hospital stay of a few days to a week for microsurgical cases."), ("Rehabilitation", "Speech, swallowing or physiotherapy support as needed.")],
      {"Duration": "3 – 10 hrs", "Anaesthesia": "General", "Hospital stay": "3 – 7 days", "Follow-up": "Long-term"},
      [("Does reconstruction delay cancer treatment?", "No. Immediate reconstruction is planned with the oncology team so it does not delay chemotherapy or radiotherapy."),
       ("Is it covered by insurance?", "Post-cancer reconstruction is generally covered under most policies.")]),

    T("children-plastic-surgery", "Children Plastic Surgery", "surgical", "baby-feet.jpg",
      "Gentle, expert care for the smallest patients.",
      ["Paediatric plastic surgery addresses birth differences and childhood injuries: cleft lip and palate, craniosynostosis, prominent ears, hand anomalies (extra or fused fingers), birthmarks, haemangiomas, burns and trauma.",
       "Timing is critical — some conditions are best treated in infancy, others when the child is older. Dr. Johar's group works with paediatricians, anaesthetists and neurosurgeons at Max Healthcare to provide safe, family-centred care."],
      ["Age-appropriate timing for the best outcome", "Child-friendly hospital environment", "Multidisciplinary team including paediatric anaesthesia", "Long-term follow-up through growth"],
      ["Cleft lip / palate", "Craniofacial and skull-shape conditions", "Congenital hand or ear differences", "Burns, scars, birthmarks and injuries"],
      [("Early consultation", "Ideally soon after diagnosis to plan timing."), ("Surgery", "Under paediatric general anaesthesia at Max Hospital."), ("Recovery", "Short hospital stay with parents at the bedside."), ("Growth follow-up", "Reviews as your child grows.")],
      {"Duration": "Condition-specific", "Anaesthesia": "General (paediatric)", "Hospital stay": "1 – 5 days", "Follow-up": "Through growth"},
      [("At what age is cleft lip repaired?", "Typically at 3–6 months of age; palate repair around 9–18 months. Each child is assessed individually.")]),

    T("cleft-craniofacial-surgery", "Cleft & Craniofacial Surgery", "surgical", "baby-feet.jpg",
      "Correcting complex conditions of the face and skull.",
      ["Craniofacial surgery treats conditions affecting the skull and facial bones — cleft lip and palate, craniosynostosis (premature fusion of skull sutures), facial asymmetry, jaw discrepancies and craniofacial trauma.",
       "Working closely with neurosurgeon Dr. Sanjeev Dua and the paediatric team, Dr. Johar performs cranial vault remodelling, cleft repairs, and corrective bone surgery with a focus on function, growth and appearance."],
      ["Combined plastic-surgical and neurosurgical expertise", "Comprehensive cleft care from infancy", "Craniosynostosis correction with proven techniques", "Facial bone reconstruction after trauma"],
      ["Infants with cleft lip / palate", "Children with abnormal head shape", "Facial deformity or asymmetry", "Facial fractures and post-traumatic deformity"],
      [("Diagnosis", "Clinical assessment and 3D imaging."), ("Team planning", "Neurosurgery, plastic surgery and paediatrics plan jointly."), ("Surgery", "Under general anaesthesia at Max Hospital."), ("Follow-up", "Growth monitoring and staged procedures if needed.")],
      {"Duration": "2 – 6 hrs", "Anaesthesia": "General", "Hospital stay": "3 – 7 days", "Follow-up": "Long-term"},
      [("Is craniosynostosis surgery safe?", "In experienced hands and a well-equipped hospital, yes. Early correction protects brain growth and gives the best head-shape result.")]),

    T("chest-surgery-pectus-correction", "Chest Surgery (Pectus Correction)", "surgical", "operating-room.jpg",
      "Correcting pigeon chest and funnel chest.",
      ["Pectus carinatum (pigeon chest) and pectus excavatum (funnel chest) are deformities of the rib cage and breastbone. Beyond appearance, severe cases can affect breathing and heart function.",
       "Dr. Johar offers thoracoplasty and customised correction — including cases associated with Marfan syndrome — restoring a normal chest contour and, in many patients, easing breathing. Watch our patient story on the video logs page."],
      ["Normalised chest contour", "Improved breathing and exercise tolerance in severe cases", "Boost in self-confidence for adolescents and adults", "Experienced team for complex and syndromic cases"],
      ["Visible chest wall deformity", "Symptoms such as breathlessness or palpitations", "Adolescents after growth spurt or adults", "Marfan syndrome and related conditions"],
      [("Assessment", "Examination, chest imaging and cardiac/pulmonary review."), ("Surgery", "Thoracoplasty / correction under general anaesthesia."), ("Recovery", "Hospital stay of a few days; restricted lifting for 6 weeks."), ("Result", "Permanent correction of contour.")],
      {"Duration": "3 – 5 hrs", "Anaesthesia": "General", "Hospital stay": "3 – 5 days", "Back to school/work": "3 – 4 weeks"},
      [("Is there a non-surgical option?", "Mild pectus carinatum in growing children can sometimes be treated with bracing. Established deformities usually require surgery.")],
      "Chest Surgery (Pectus)"),

    T("facial-plasty-maxillofacial-surgery", "Facial Plasty & Maxillofacial Surgery", "surgical", "surgeon-portrait.jpg",
      "Reconstruction and refinement of the facial skeleton.",
      ["Maxillofacial surgery treats the bones and soft tissues of the face and jaws — facial fractures, jaw deformities affecting the bite, tumours, post-traumatic asymmetry and facial nerve problems. Facial plasty encompasses the soft-tissue reconstruction and aesthetic refinement that goes with it.",
       "Dr. Johar's group provides comprehensive facial reconstruction, from acute trauma at Max Hospital's emergency department to elective corrective jaw and cheekbone surgery."],
      ["Restoration of facial symmetry and function", "Fixation of facial fractures with precise plating", "Corrective jaw surgery for bite and profile", "Soft-tissue and nerve reconstruction"],
      ["Facial injuries and fractures", "Jaw misalignment or asymmetry", "Post-traumatic or post-tumour deformity", "Facial paralysis needing reanimation"],
      [("Assessment", "Clinical examination and CT imaging."), ("Planning", "3D planning for complex bone corrections."), ("Surgery", "Under general anaesthesia."), ("Follow-up", "Bite, function and appearance monitored over months.")],
      {"Duration": "1 – 6 hrs", "Anaesthesia": "General", "Hospital stay": "1 – 5 days", "Follow-up": "3 – 12 months"},
      [("Are the scars visible?", "Most incisions are inside the mouth, in the hairline or within natural creases, leaving minimal visible scarring.")],
      "Facial Plasty & Maxillofacial"),

    T("female-genital-cosmetic-surgery", "Female Genital Cosmetic Surgery", "surgical", "consultation.jpg",
      "Discreet, comfortable and confidential care.",
      ["Female genital cosmetic surgery addresses functional and aesthetic concerns of the external genitalia — labiaplasty for enlarged or asymmetric labia that cause discomfort with clothing, exercise or intimacy; and vaginal tightening after childbirth.",
       "These are common, safe procedures performed with complete confidentiality. Dr. Johar and the team ensure a private, respectful consultation and a fast, comfortable recovery."],
      ["Relief from chafing and discomfort", "Improved comfort and confidence", "Short, day-care procedure", "Complete privacy and discretion"],
      ["Discomfort from enlarged or asymmetric labia", "Changes after childbirth", "Adults in good health", "Realistic expectations"],
      [("Private consultation", "Discussion of concerns and options."), ("Procedure", "Local or general anaesthesia; 1–2 hours."), ("Recovery", "Rest for a few days; avoid strenuous activity for 4–6 weeks."), ("Result", "Healed and settled by 6–8 weeks.")],
      {"Duration": "1 – 2 hrs", "Anaesthesia": "Local / general", "Hospital stay": "Day-care", "Back to work": "3 – 5 days"},
      [("Is the consultation confidential?", "Completely. Your privacy is a priority at every step.")],
      "Female Genital Cosmetic Surgery"),

    T("lymphedema", "Lymphedema", "surgical", "massage.jpg",
      "Modern surgical and non-surgical relief for chronic swelling.",
      ["Lymphedema is chronic swelling — usually of an arm or leg — caused by damage to or malformation of the lymphatic system, often after cancer surgery or radiotherapy. Untreated, it can lead to heaviness, infections and hardening of the tissue.",
       "Treatment ranges from complete decongestive therapy and compression to modern microsurgical procedures — lymphaticovenous anastomosis (LVA), vascularised lymph node transfer and debulking liposuction — that can significantly reduce swelling and improve quality of life."],
      ["Reduces limb volume and heaviness", "Fewer episodes of cellulitis", "Microsurgical options where conservative care fails", "Coordinated with oncology and physiotherapy"],
      ["Arm swelling after breast cancer treatment", "Leg swelling after pelvic surgery or radiotherapy", "Primary (congenital) lymphedema", "Recurrent infections in a swollen limb"],
      [("Assessment", "Clinical staging and lymphatic imaging."), ("Conservative care", "Compression, manual drainage and skin care."), ("Surgery", "LVA, lymph node transfer or liposuction depending on stage."), ("Maintenance", "Ongoing compression and follow-up.")],
      {"Duration": "2 – 5 hrs", "Anaesthesia": "General", "Hospital stay": "1 – 3 days", "Follow-up": "Long-term"},
      [("Can lymphedema be cured?", "It is a chronic condition, but modern treatment can dramatically reduce swelling and symptoms, especially when started early.")]),

    # ---------------- NON-SURGICAL ----------------
    T("acne-and-acne-scars", "Acne & Acne Scars", "nonsurgical", "skin-closeup.jpg",
      "Clear active acne and smooth the marks it leaves behind.",
      ["Acne is treated medically first — with a prescription skincare regimen, oral medications where needed and in-clinic peels or light therapy to bring breakouts under control.",
       "Once acne is quiet, scars are addressed with a combination approach: microneedling with PRP, fractional laser resurfacing, subcision for tethered scars, TCA CROSS for ice-pick scars, and fillers for volume loss. Most patients see steady improvement over a series of sessions."],
      ["Fewer breakouts and less inflammation", "Visibly smoother skin texture", "Combination protocols customised to scar type", "Minimal downtime"],
      ["Active or recurrent acne", "Rolling, boxcar or ice-pick scars", "Post-acne pigmentation", "All skin types (protocols adjusted for Indian skin)"],
      [("Skin analysis", "Identify acne type, scar type and skin tone."), ("Control", "Medical therapy and peels to settle active acne."), ("Resurface", "Microneedling / laser / subcision sessions 4–6 weeks apart."), ("Maintain", "Skincare and sun protection to hold the result.")],
      {"Sessions": "3 – 6", "Anaesthesia": "Topical numbing", "Downtime": "0 – 5 days", "Results": "Progressive over months"},
      [("Are lasers safe for Indian skin?", "Yes, when the right device and settings are used. We select fractional and non-ablative technologies proven safe for darker skin types.")]),

    T("hair-restoration", "Hair Restoration (Hair Fall / Hair Loss)", "nonsurgical", "hair-care.jpg",
      "Stop the fall, restore the density.",
      ["Hair fall has many causes — genetics, hormonal changes, stress, illness (including post-Covid), nutritional deficiency and scalp conditions. Correct diagnosis is the foundation of successful treatment.",
       "Dr. Johar offers medical therapy, PRP (platelet-rich plasma) scalp treatments, growth-factor and mesotherapy sessions and low-level laser therapy — and, for established pattern baldness, hair transplantation."],
      ["Reduces shedding and strengthens existing hair", "PRP uses your own growth factors — no drugs", "Improves density and hair quality", "Pathway to transplant if needed"],
      ["Increasing hair fall or thinning", "Early pattern hair loss in men or women", "Post-illness or postpartum shedding", "Patients wanting to boost transplant results"],
      [("Consultation", "Scalp examination, history and blood tests if needed."), ("Plan", "Medical regimen ± PRP / mesotherapy course."), ("Sessions", "PRP typically 4–6 sessions, 4 weeks apart."), ("Maintenance", "Periodic top-up sessions.")],
      {"Sessions": "4 – 6", "Anaesthesia": "Topical", "Downtime": "None", "Results": "3 – 6 months"},
      [("Does PRP really work?", "For early to moderate thinning, PRP reliably reduces shedding and thickens hair in most patients, particularly when combined with medical therapy.")],
      "Hair Restoration"),

    T("face-care-rejuvenation", "Face Care & Rejuvenation", "nonsurgical", "facial-spa.jpg",
      "Healthy, glowing skin at every age.",
      ["Our face care programmes combine medical-grade facials, HydraFacial-style deep cleansing, peels, LED therapy, microneedling and skin boosters to improve texture, tone, hydration and radiance.",
       "Every programme starts with a skin analysis and is adjusted to your skin type and season — from a pre-event glow to a long-term anti-ageing plan."],
      ["Deep cleansing, hydration and glow", "Even tone and refined pores", "Stimulates collagen for firmer skin", "No downtime — ideal before events"],
      ["Dull or dehydrated skin", "Uneven tone or pigmentation", "Early lines and loss of glow", "Anyone wanting a healthy skincare routine"],
      [("Analysis", "Skin type and concern assessment."), ("Treatment", "Customised in-clinic session, 45–60 minutes."), ("Home care", "Prescription skincare plan."), ("Maintain", "Monthly or seasonal sessions.")],
      {"Duration": "45 – 60 min", "Anaesthesia": "None", "Downtime": "None", "Results": "Immediate glow, cumulative"},
      [("How often should I have a medical facial?", "Every 4–6 weeks matches the skin's renewal cycle; your plan will be personalised.")]),

    T("lasers", "Lasers", "nonsurgical", "facial-brush.jpg",
      "Precision light for pigmentation, scars, hair and rejuvenation.",
      ["Laser and light-based devices treat a wide range of concerns: unwanted hair, pigmentation and melasma, acne scars, fine lines, open pores, tattoos, vascular lesions and skin laxity.",
       "We use technologies chosen for safety in Indian skin — including Q-switched / pico lasers for pigment, fractional lasers for resurfacing and diode lasers for hair removal — with settings tailored to each patient."],
      ["Targeted treatment with minimal downtime", "Safe protocols for darker skin", "Permanent hair reduction", "Improves texture, tone and scars"],
      ["Unwanted facial or body hair", "Pigmentation, tan or melasma", "Acne scars or open pores", "Tattoo removal"],
      [("Consultation", "Concern assessment and patch test if needed."), ("Session", "15–60 minutes depending on area."), ("Course", "Usually 4–8 sessions at 4–6 week intervals."), ("Aftercare", "Sun protection and gentle skincare.")],
      {"Sessions": "4 – 8", "Anaesthesia": "Topical numbing (if needed)", "Downtime": "0 – 5 days", "Results": "Progressive"},
      [("Is laser hair removal permanent?", "It gives long-term hair reduction of 80–90% after a full course; occasional maintenance sessions may be needed.")]),

    T("scars", "Scars", "nonsurgical", "cream-hand.jpg",
      "Flatten, fade and soften scars of every kind.",
      ["Scars from surgery, injury, burns or acne can be raised (hypertrophic or keloid), depressed, discoloured or tight. Treatment is chosen by scar type: silicone therapy and steroid injections for raised scars, lasers for redness and texture, microneedling and subcision for depressed scars, and surgical revision where the scar direction or width can be improved.",
       "As a plastic surgeon, Dr. Johar offers the entire spectrum from non-invasive to surgical scar revision."],
      ["Flatter, softer, less visible scars", "Relief of itching, pain and tightness", "Non-surgical and surgical options", "Keloid management with combination therapy"],
      ["Surgical or traumatic scars", "Keloids and hypertrophic scars", "Burn scars and contractures", "Acne scars"],
      [("Assessment", "Scar type, age and location."), ("Non-invasive phase", "Silicone, injections, laser or microneedling."), ("Revision if needed", "Surgical re-orientation or Z-plasty."), ("Maintenance", "Sun protection and silicone.")],
      {"Sessions": "1 – 6", "Anaesthesia": "Local / topical", "Downtime": "Minimal", "Results": "Gradual over months"},
      [("Can a scar be removed completely?", "No scar can be erased, but most can be made significantly less noticeable — often to the point where others no longer see them.")]),

    T("skin-tightening", "Skin Tightening", "nonsurgical", "face-natural.jpg",
      "Firmer skin without surgery.",
      ["Non-surgical skin tightening uses radiofrequency (RF), HIFU (high-intensity focused ultrasound) or RF-microneedling to heat the deeper layers of skin, stimulating new collagen and gradually tightening lax skin of the face, neck, jawline, abdomen and arms.",
       "It is ideal for mild-to-moderate laxity, for younger patients wanting prevention, and for maintaining the results of surgery."],
      ["Lifts and firms without incisions", "No downtime", "Progressive, natural improvement", "Suitable for face and body"],
      ["Early jowls or loose neck skin", "Mild laxity of the abdomen or arms", "Patients not ready for surgery", "Maintenance after facelift or liposuction"],
      [("Consultation", "Assess laxity and select RF / HIFU / RF-microneedling."), ("Session", "30–90 minutes; mild warmth."), ("Course", "1–3 sessions depending on device."), ("Result", "Collagen builds over 2–6 months.")],
      {"Sessions": "1 – 3", "Anaesthesia": "Topical (if needed)", "Downtime": "None", "Results": "2 – 6 months"},
      [("How long do results last?", "Typically 12–18 months, after which a maintenance session is recommended.")]),

    T("prp", "PRP (Platelet-Rich Plasma)", "nonsurgical", "woman-smiling.jpg",
      "Your body's own growth factors for skin and hair.",
      ["PRP concentrates the platelets from a small sample of your own blood. Platelets release growth factors that stimulate repair, collagen production and hair follicle activity. Because it comes from you, there is no risk of allergy.",
       "We use PRP for hair restoration, under-eye rejuvenation, acne scars (with microneedling — the 'vampire facial'), skin quality and to speed healing after procedures."],
      ["Natural — uses your own blood", "Improves skin texture and glow", "Reduces hair fall and thickens hair", "Minimal downtime"],
      ["Hair thinning", "Dull skin, fine lines, dark circles", "Acne scars", "Anyone seeking a natural approach"],
      [("Blood draw", "A small sample is taken."), ("Preparation", "Centrifuged to concentrate platelets."), ("Application", "Injected or microneedled into the target area."), ("Course", "3–6 sessions, 4 weeks apart.")],
      {"Duration": "45 – 60 min", "Anaesthesia": "Topical", "Downtime": "0 – 1 day", "Results": "6 – 12 weeks"},
      [("Is PRP painful?", "Topical numbing keeps it very comfortable; you may feel mild pressure.")],
      "PRP"),

    T("botox", "Botox (Anti-Wrinkle Injections)", "nonsurgical", "woman-pink.jpg",
      "Soften lines, keep expression.",
      ["Botulinum toxin relaxes the small muscles that cause dynamic wrinkles — frown lines, forehead lines and crow's feet — for a smoother, more relaxed look. It is also used for a subtle brow lift, jaw slimming (masseter), gummy smile, neck bands, and to treat excessive sweating and migraines.",
       "Dr. Johar's philosophy is 'less is more': precise, conservative dosing so you look refreshed and still move naturally."],
      ["Smooths frown, forehead and eye lines", "Quick 10-minute treatment", "No downtime", "Preventive 'baby Botox' for younger patients"],
      ["Dynamic wrinkles that show on expression", "Jaw clenching or a wide lower face", "Excess sweating of palms or underarms", "Adults not pregnant or breastfeeding"],
      [("Consultation", "Assess expression and plan injection points."), ("Treatment", "A few tiny injections; ~10 minutes."), ("Onset", "Effect begins in 3–5 days, full at 2 weeks."), ("Duration", "3–5 months, then repeat.")],
      {"Duration": "10 – 15 min", "Anaesthesia": "None / ice", "Downtime": "None", "Results": "3 – 5 months"},
      [("Will I look frozen?", "Not with conservative dosing. Our aim is a natural, rested look — you will still express fully.")]),

    T("fillers", "Dermal Fillers", "nonsurgical", "woman-dark.jpg",
      "Restore volume, define contours.",
      ["Hyaluronic acid fillers restore lost volume and enhance contours — cheeks, lips, jawline, chin, temples, under-eye hollows and nasolabial folds. Results are immediate, natural, and reversible if ever needed.",
       "As a plastic surgeon with a deep understanding of facial anatomy, Dr. Johar places filler with precision for a balanced, refreshed result rather than an over-filled one."],
      ["Immediate, natural volume and definition", "Reversible and adjustable", "Lasts 9–18 months", "Non-surgical alternative to implants for chin/cheek"],
      ["Volume loss with age", "Thin lips or a weak chin", "Under-eye hollows and dark circles", "Deep folds and marionette lines"],
      [("Consultation", "Facial assessment and plan."), ("Treatment", "Numbing cream; injections take 20–40 minutes."), ("Aftercare", "Mild swelling for 1–3 days."), ("Review", "Follow-up at 2 weeks.")],
      {"Duration": "20 – 40 min", "Anaesthesia": "Topical / lidocaine in filler", "Downtime": "0 – 2 days", "Results": "9 – 18 months"},
      [("Are fillers safe?", "Yes, when injected by a trained expert with knowledge of anatomy. We use only reputable, approved products.")]),

    T("bridalplasty", "Bridalplasty", "nonsurgical", "makeup.jpg",
      "Your wedding-day glow — planned from months ahead.",
      ["Bridalplasty is a personalised programme of treatments timed before your wedding: skin brightening, medical facials, peels, laser hair removal, acne control, Botox and fillers, body contouring and hair health — scheduled so everything settles perfectly by the big day.",
       "We build a countdown calendar starting 3–6 months out, with the gentlest treatments in the final weeks. Grooms are welcome too."],
      ["Radiant, camera-ready skin", "Structured 3–6 month timeline", "Combines skin, hair and body treatments", "For brides and grooms"],
      ["Brides and grooms 3–6 months before the wedding", "Anyone preparing for a major event", "All skin types", "Those wanting a safe, planned approach"],
      [("Consult (3–6 months out)", "Skin analysis and countdown plan."), ("Correct", "Peels, lasers, acne and pigmentation control."), ("Refine (6–8 weeks out)", "Botox, fillers, skin boosters."), ("Glow (1–2 weeks out)", "Medical facial and hydration.")],
      {"Duration": "3 – 6 month plan", "Anaesthesia": "None / topical", "Downtime": "Planned around events", "Results": "Peak on your day"},
      [("When should I start?", "Ideally 6 months before; even 6–8 weeks allows a meaningful glow programme.")]),

    T("thread-lift", "Thread Lift", "nonsurgical", "mature-woman.jpg",
      "A lunchtime lift for early sagging.",
      ["A thread lift uses dissolvable PDO / PLLA threads placed under the skin to lift sagging cheeks, jowls, brows and neck, and to stimulate collagen. It gives an immediate, subtle lift with results that improve over months as new collagen forms.",
       "It is ideal for patients with mild-to-moderate laxity who are not ready for a surgical facelift."],
      ["Immediate lift with no incisions", "Stimulates collagen for lasting firmness", "30–60 minute procedure", "Minimal downtime"],
      ["Early jowls or sagging cheeks", "Mild neck laxity", "Patients aged ~35–55", "Those seeking a non-surgical lift"],
      [("Consultation", "Assess laxity and thread plan."), ("Procedure", "Local anaesthesia; threads placed via fine needles."), ("Recovery", "Mild swelling for a few days."), ("Result", "Immediate, improving over 3 months; lasts 12–18 months.")],
      {"Duration": "30 – 60 min", "Anaesthesia": "Local", "Downtime": "1 – 3 days", "Results": "12 – 18 months"},
      [("Does it replace a facelift?", "No — it is a gentler option for early sagging. Significant laxity is better treated surgically.")]),

    T("chemical-peel", "Chemical Peel", "nonsurgical", "facial-brush.jpg",
      "Fresh, even, luminous skin.",
      ["Chemical peels apply a controlled solution — glycolic, salicylic, lactic, mandelic, TCA or combination peels — to exfoliate the outer layers of skin, treating pigmentation, tan, acne, dullness and fine lines.",
       "Peel strength is chosen for your skin type and concern; superficial peels have no downtime while medium peels give a more dramatic result with a few days of flaking."],
      ["Brighter, more even tone", "Reduces acne and pigmentation", "Smoother texture and finer pores", "Customisable strength"],
      ["Tan, pigmentation or melasma", "Acne-prone or oily skin", "Dull, tired skin", "Fine lines"],
      [("Consultation", "Peel selection."), ("Session", "15–30 minutes."), ("After", "Mild flaking for superficial peels; 3–7 days for medium."), ("Course", "4–6 sessions, 2–4 weeks apart.")],
      {"Duration": "15 – 30 min", "Anaesthesia": "None", "Downtime": "0 – 7 days", "Results": "Cumulative"},
      [("Will my skin peel visibly?", "Superficial peels usually cause only mild flaking; you will be told what to expect for your peel.")]),

    T("microdermabrasion", "Microdermabrasion", "nonsurgical", "facial-spa.jpg",
      "Gentle resurfacing for instant radiance.",
      ["Microdermabrasion uses fine crystals or a diamond tip to gently exfoliate the outermost layer of skin, unclog pores and stimulate renewal. It leaves skin brighter, smoother and better able to absorb skincare.",
       "It is a comfortable, no-downtime treatment often combined with a peel or medical facial."],
      ["Instant glow with no downtime", "Reduces blackheads and congestion", "Softens fine lines and mild scars", "Boosts skincare absorption"],
      ["Dull or congested skin", "Mild acne scars or pigmentation", "Anyone wanting a quick refresh", "All skin types"],
      [("Cleanse", "Skin is prepared."), ("Exfoliate", "Diamond-tip resurfacing, 20–30 minutes."), ("Nourish", "Mask and moisturiser."), ("Repeat", "Every 3–4 weeks.")],
      {"Duration": "20 – 30 min", "Anaesthesia": "None", "Downtime": "None", "Results": "Immediate"},
      [("Is it painful?", "No — it feels like a gentle sanding sensation and is very well tolerated.")]),

    T("permanent-makeup", "Permanent Makeup", "nonsurgical", "makeup.jpg",
      "Wake up ready — brows, lips and eyeliner.",
      ["Permanent (semi-permanent) makeup uses medical-grade pigments implanted into the upper dermis to define eyebrows (microblading / powder brows), lips (lip blush) and eyeliner. It is also used to camouflage scars and restore the areola after breast reconstruction.",
       "Performed in a clinical setting with strict hygiene, results last 1–3 years and can be refreshed."],
      ["Defined brows, lips and eyes every day", "Saves time and looks natural", "Scar and areola camouflage after surgery", "Fades gracefully; can be refreshed"],
      ["Sparse or asymmetric brows", "Pale or uneven lip colour", "Alopecia or brow loss", "Post-reconstruction areola restoration"],
      [("Design", "Shape and colour agreed with you."), ("Procedure", "Topical numbing; 1–2 hours."), ("Healing", "Slight darkening then softening over 2 weeks."), ("Touch-up", "At 6–8 weeks.")],
      {"Duration": "1 – 2 hrs", "Anaesthesia": "Topical", "Downtime": "None", "Results": "1 – 3 years"},
      [("Is it really permanent?", "It is semi-permanent — pigments fade over 1–3 years, which lets the shape be adjusted as trends and your face change.")]),

    T("vaginal-rejuvenation", "Vaginal Rejuvenation", "nonsurgical", "woman-smiling.jpg",
      "Non-surgical restoration of comfort and confidence.",
      ["Non-surgical vaginal rejuvenation uses radiofrequency or laser energy to stimulate collagen and improve tissue tone. It helps with laxity after childbirth, mild urinary leakage, dryness and discomfort — with no incisions and no downtime.",
       "Treatment is quick and private; surgical options are also available where appropriate."],
      ["Improved tone and comfort", "Helps mild stress incontinence and dryness", "No surgery, no downtime", "Discreet, private care"],
      ["Laxity after childbirth", "Mild stress urinary incontinence", "Post-menopausal dryness", "Women seeking a non-surgical option"],
      [("Private consultation", "Discussion of concerns."), ("Session", "15–30 minutes, comfortable."), ("Course", "Usually 3 sessions, 4 weeks apart."), ("Maintenance", "Annual session.")],
      {"Duration": "15 – 30 min", "Anaesthesia": "None", "Downtime": "None", "Results": "After 2–3 sessions"},
      [("Is it painful?", "No; most women describe mild warmth only.")]),
]

CAT_MAP = {"surgical": "surgical-treatments", "nonsurgical": "nonsurgical-treatments"}

# --- Additional category-only bundles for Cosmetic Medicine / Preventive / Age Reversal ----
CATEGORY_TREATMENTS = {
    "cosmetic-medicine": ["face-care-rejuvenation", "chemical-peel", "microdermabrasion", "prp", "hair-restoration", "acne-and-acne-scars", "lasers", "permanent-makeup"],
    "preventive-aesthetics": ["botox", "skin-tightening", "face-care-rejuvenation", "prp", "chemical-peel", "lasers", "bridalplasty"],
    "age-reversal": ["facelift", "blepharoplasty-eyelid-surgery", "brow-lift", "thread-lift", "fillers", "botox", "skin-tightening", "lasers"],
}

OFFERS = [
    {"tag": "New Patients", "title": "Complimentary Skin Analysis", "desc": "Book any non-surgical consultation and receive a detailed skin analysis with a personalised care plan.", "note": "Valid at Noida clinic. One per patient."},
    {"tag": "Package", "title": "PRP Hair Course — Save 15%", "desc": "Book a course of 4 PRP scalp sessions and save 15% over individual sessions.", "note": "Course to be completed within 6 months."},
    {"tag": "Seasonal", "title": "Laser Hair Removal — Full Body Plan", "desc": "Choose a full-body laser hair removal package for a special seasonal price with flexible session scheduling.", "note": "Ask our team for current pricing."},
    {"tag": "Bridal", "title": "Bridalplasty Countdown Programme", "desc": "A structured 3-month glow programme for brides and grooms — with a complimentary pre-wedding hydration facial.", "note": "Book at least 8 weeks before the event."},
]

FELLOWSHIPS = [
    {"title": "Fellowship in Aesthetic & Reconstructive Surgery", "dur": "12 months", "desc": "A structured, hands-on fellowship for qualified plastic surgeons (MCh / DNB) covering aesthetic surgery of the face, breast and body, microsurgical reconstruction, craniofacial and cancer reconstruction across Max Healthcare hospitals."},
    {"title": "Short-Term Fellowship in Cosmetic Surgery", "dur": "3 – 6 months", "desc": "Focused exposure to high-volume aesthetic practice — rhinoplasty, liposuction, body contouring, breast surgery and non-surgical aesthetics — with graded operative involvement."},
    {"title": "Fellowship in Microsurgery & Limb Preservation", "dur": "6 months", "desc": "Free-flap reconstruction, lymphatic surgery and diabetic-foot limb salvage in a multidisciplinary environment."},
]

# --- Blog: additional articles authored for the redesign ---
NEW_ARTICLES = [
    {"slug": "plastic-surgery-vs-cosmetic-surgery", "title": "Plastic Surgery vs Cosmetic Surgery: What's the Difference?", "date": "15 Jun 2026", "cat": "Patient Education", "img": "consultation.jpg",
     "excerpt": "The two terms are used interchangeably, but they are not the same. Understanding the difference helps you choose the right specialist.",
     "blocks": [
        {"p": "Patients often use 'plastic surgery' and 'cosmetic surgery' as if they mean the same thing. They overlap, but the difference matters — especially when you are choosing who should operate on you."},
        {"h": "Plastic surgery: restoring form and function"},
        {"p": "Plastic surgery is a recognised surgical specialty. Training covers the reconstruction of defects caused by birth conditions (cleft lip and palate, craniofacial differences), trauma and burns, cancer resection, infection and disease. A plastic surgeon completes years of supervised training in the entire field before qualifying (MCh / DNB in Plastic Surgery in India)."},
        {"h": "Cosmetic surgery: enhancing appearance"},
        {"p": "Cosmetic — or aesthetic — surgery is the part of plastic surgery that focuses on enhancing appearance: rhinoplasty, facelift, liposuction, breast augmentation and so on. Because it is elective, doctors from other backgrounds sometimes offer 'cosmetic' procedures after short courses. A qualified plastic surgeon, however, has trained in cosmetic surgery as part of a much broader surgical education."},
        {"h": "Why the distinction matters"},
        {"ul": ["A plastic surgeon understands the deeper anatomy from reconstructive work — which is what makes aesthetic results safe and natural.", "Complications are rare, but when they happen you want a surgeon trained to manage them.", "Reconstructive and cosmetic goals often go together: a nose that breathes better and looks better; a breast rebuilt after cancer to look natural."]},
        {"h": "How to check"},
        {"p": "Ask about qualifications (MCh or DNB in Plastic Surgery), membership of the Association of Plastic Surgeons of India, and where the surgery will be performed. Dr. Manoj Johar and his team operate at accredited Max Healthcare hospitals and offer both reconstructive and cosmetic surgery — so your treatment plan is chosen for you, not limited by what the doctor can offer."},
     ]},
    {"slug": "how-to-choose-best-plastic-surgeon-india", "title": "How to Choose the Best Plastic Surgeon in India", "date": "13 Jun 2026", "cat": "Patient Education", "img": "surgeon-portrait.jpg",
     "excerpt": "Qualifications, hospital, honesty and rapport — a practical checklist for one of the most important decisions you will make.",
     "blocks": [
        {"p": "Choosing a plastic surgeon is not like choosing a salon. It is a medical decision with long-term consequences. Here is the checklist we recommend to our own friends and family."},
        {"h": "1. Verify qualifications"},
        {"p": "Look for MCh or DNB in Plastic Surgery — the formal super-specialty degrees. Membership of the Association of Plastic Surgeons of India (APSI) and the Indian Association of Aesthetic Plastic Surgeons (IAAPS) indicates a surgeon who is part of the professional community."},
        {"h": "2. Ask where the surgery is done"},
        {"p": "Accredited hospitals with full anaesthesia teams, intensive care and blood bank are safer than small clinics — particularly for procedures under general anaesthesia. Dr. Johar operates exclusively at Max Healthcare hospitals in Noida, Vaishali and Patparganj."},
        {"h": "3. Look for honesty, not salesmanship"},
        {"p": "A good surgeon tells you when a procedure is not right for you, when a non-surgical option would do, and what the limits of a result are. Be wary of anyone who promises perfection or pressures you to decide on the spot."},
        {"h": "4. Review real experience"},
        {"p": "Ask how often the surgeon performs the specific procedure you are considering, look at before-and-after photographs of similar patients, and read patient testimonials."},
        {"h": "5. Trust the rapport"},
        {"p": "You should feel heard, understood and unhurried. The consultation is a preview of the care you will receive throughout your journey."},
        {"blockquote": "The right surgeon is not the one who says yes the fastest — it is the one who helps you make the right decision."},
     ]},
    {"slug": "complete-guide-rhinoplasty-surgery", "title": "Complete Guide to Rhinoplasty Surgery", "date": "8 Jun 2026", "cat": "Surgical", "img": "woman-pink.jpg",
     "excerpt": "From consultation to the final result a year later — everything you need to know about nose reshaping surgery.",
     "blocks": [
        {"p": "Rhinoplasty is one of the most requested — and most technically demanding — aesthetic procedures. Because the nose sits at the centre of the face, even small changes have a big effect on overall harmony."},
        {"h": "What rhinoplasty can do"},
        {"ul": ["Reduce a dorsal hump and straighten the bridge", "Refine a bulbous or drooping tip", "Narrow wide nostrils", "Correct asymmetry after injury", "Improve breathing by straightening the septum (septorhinoplasty)"]},
        {"h": "Open vs closed technique"},
        {"p": "In a closed rhinoplasty all incisions are inside the nostrils. In an open rhinoplasty a tiny incision across the columella allows the surgeon to see the framework directly — useful for tip work and revisions. The resulting scar is almost invisible once healed."},
        {"h": "The day of surgery"},
        {"p": "Rhinoplasty is performed under general anaesthesia and takes two to three hours. Most patients go home the same day or after one night with a small external splint."},
        {"h": "Recovery timeline"},
        {"ul": ["Week 1: splint on, bruising around the eyes settles", "Week 2: presentable in public, back to work", "Weeks 4–6: most swelling gone; exercise resumed", "Months 6–12: the tip refines to its final shape"]},
        {"h": "Choosing your surgeon"},
        {"p": "Because the nose must both look natural and function well, choose a plastic surgeon with a structural approach who will discuss realistic goals with you — and who can show you results on faces like yours."},
     ]},
    {"slug": "liposuction-vs-tummy-tuck", "title": "Liposuction vs Tummy Tuck: Which One is Better?", "date": "1 Jun 2026", "cat": "Surgical", "img": "body-fitness.jpg",
     "excerpt": "They are often confused, but they solve different problems. Here is how to tell which one you need — or whether it is both.",
     "blocks": [
        {"p": "'Should I have liposuction or a tummy tuck?' is one of the most common questions in our clinic. The answer depends on one thing: what is actually causing the shape you want to change — fat, skin, or muscle."},
        {"h": "Liposuction removes fat"},
        {"p": "Liposuction suctions out localised fat through tiny incisions. It works beautifully when the skin is firm enough to shrink back over the new contour. It does nothing for loose skin or separated muscles."},
        {"h": "A tummy tuck removes skin and tightens muscle"},
        {"p": "An abdominoplasty removes loose skin (and the stretch marks on it), repairs the separated abdominal muscles that pregnancy or weight change leave behind, and re-drapes the abdomen flat. Fat is often removed at the same time."},
        {"h": "A quick self-test"},
        {"ul": ["Pinch the skin: if there is a thick layer of fat but skin snaps back — liposuction.", "If the skin hangs, folds or has stretch marks — tummy tuck.", "If your abdomen bulges even when you are slim — the muscles need repair (tummy tuck).", "Often the best answer is both, in one operation."]},
        {"h": "Recovery compared"},
        {"p": "Liposuction is day-care with a return to work in a few days. A tummy tuck needs a night or two in hospital and about two weeks off — but it is the only procedure that corrects skin and muscle."},
        {"p": "The right choice comes from an honest examination. Dr. Johar will show you exactly what each option can achieve for your body."},
     ]},
    {"slug": "first-plastic-surgery-consultation-what-to-expect", "title": "What to Expect During Your First Plastic Surgery Consultation", "date": "16 May 2026", "cat": "First Visit", "img": "consultation.jpg",
     "excerpt": "Nervous about the first appointment? Here is exactly what happens — and how to prepare so you get the most from it.",
     "blocks": [
        {"p": "Your first consultation is the most important step in your journey. It is a conversation, not a commitment — and being prepared makes it far more useful."},
        {"h": "What we will ask you"},
        {"ul": ["What concerns you and what result you hope for", "Your medical history, medications, allergies and previous surgery", "Lifestyle factors: smoking, exercise, upcoming events", "Whether you have had cosmetic treatments before"]},
        {"h": "What we will do"},
        {"p": "Dr. Johar will examine the area, take clinical photographs (kept confidential), and explain your options — surgical, non-surgical or none. You will hear the benefits, limitations, risks and recovery for each, and receive a written estimate."},
        {"h": "How to prepare"},
        {"ul": ["Write your questions down beforehand", "Bring a list of medications and any previous reports", "Bring photographs of yourself at a younger age if relevant (for rejuvenation)", "Come without makeup if the concern is facial skin"]},
        {"h": "After the consultation"},
        {"p": "Take your time. There is never pressure to decide on the day. When you are ready, our coordinators will help you plan tests, dates and everything you need."},
     ]},
    {"slug": "plastic-surgery-recovery-tips-faster-healing", "title": "Plastic Surgery Recovery Tips for Faster Healing", "date": "10 May 2026", "cat": "Recovery", "img": "hospital-room.jpg",
     "excerpt": "Small habits make a big difference to how quickly — and how well — you heal after surgery.",
     "blocks": [
        {"p": "How you look after yourself in the weeks after surgery has a real influence on your final result. These are the tips we give every patient."},
        {"h": "Before surgery"},
        {"ul": ["Stop smoking at least 4 weeks before — nicotine starves healing tissue of oxygen", "Avoid aspirin, ibuprofen, vitamin E and herbal supplements that increase bleeding, as advised", "Eat well and stay hydrated; get your iron and protein levels checked"]},
        {"h": "The first week"},
        {"ul": ["Rest, but walk short distances several times a day to prevent clots", "Keep the operated area elevated where advised", "Take medications exactly as prescribed — including antibiotics to completion", "Wear your compression garment or dressings as instructed"]},
        {"h": "Nutrition for healing"},
        {"p": "Protein (dal, paneer, eggs, fish, chicken), vitamin C (citrus, amla), zinc (nuts, seeds) and plenty of water all support tissue repair. Avoid alcohol until cleared."},
        {"h": "Scar care"},
        {"p": "Once wounds are healed, silicone gel or sheets, gentle massage and strict sun protection for a year help scars fade to fine lines."},
        {"h": "When to call us"},
        {"p": "Fever, increasing pain, redness or discharge, sudden swelling on one side, or breathlessness — call the clinic immediately. Our team is available for any concern, big or small."},
     ]},
]

# Photo assignments for the scraped 2022 blog articles
OLD_ARTICLE_META = {
    "10 Ways to get glowing skin in summer": ("10-ways-to-get-glowing-skin-in-summer", "Skin Care", "facial-spa.jpg"),
    "7 Ways for hair care in summer": ("7-ways-for-hair-care-in-summer", "Hair Care", "hair-care.jpg"),
    "Facts about Grey Hair: What to Know": ("facts-about-grey-hair-what-to-know", "Hair Care", "mature-woman.jpg"),
    "Heatwave: 5 best and super hydrating foods to beat the heat": ("heatwave-5-hydrating-foods-to-beat-the-heat", "Wellness", "woman-smiling.jpg"),
    "How to use hair serum: Dos and Don'ts": ("how-to-use-hair-serum-dos-and-donts", "Hair Care", "hair-care.jpg"),
    "Signs You Don't Drink Enough Water": ("signs-you-dont-drink-enough-water", "Wellness", "cream-hand.jpg"),
}
